### ISSUE TITLE
Download not working - Fedora 26

### ISSUE THREAD

**Issue by joshbranham** [FedoraQt/MediaWriter#120]
In the windows version, when creating USB for Fedora 26 workstation, the default does not include a download. The screen is blank, versus when you pick 25 or 24 it shows a download link and proceeds to download when you click Create Live USB

**Comment by MartinBriza** [comment]
The screen is blank? Huh, can you please show me how did it look?

**Comment by joshphp** [comment]
I don't have windows running anymore, but you know when you select the fedora version it tells you the download size on the right? So if you pick Fedora 25 or 24 it shows the size but 26 it shows nothing. And when it goes to build the USB it takes no time at all and does not boot. 

Josh

**Comment by MartinBriza** [comment]
Well, first it shows no size because it doesn't know about it. It's then fetched from the web. It should be there after the download is finished, though.
However, it's possible there's a bug in the downloader code, making it write an empty image by mistake. I gotta admit the code in that part is not as good as I'd wish it to be...

**Comment by grulja** [comment]
Closing. Feel free to reopen if you still have same problem with latest FMW.
