### ISSUE TITLE
Win10 error "Destination drive is not writable. Couldn't open the driver for writing"

### ISSUE THREAD

**Issue by rafaelrosars** [FedoraQt/MediaWriter#145]
I'm trying to write fedora workstation 27 to USB (already tried 3 differents usb drivers).
Fedora Media Writer 4.1.1
Windows 10 x64

![sem titulo](https://user-images.githubusercontent.com/11970952/34421032-14bf2772-ebf4-11e7-9a66-de19bc58457f.png)

**Comment by MartinBriza** [comment]
Do you run any antivirus software or something related to disk management on your computer? This was usually the cause of the problems in the past.

**Comment by rafaelrosars** [comment]
I use Norton Security but even disabling it, the same error occurs.

**Comment by MartinBriza** [comment]
There's most likely some application continuosly accessing the drive, preventing FMW from opening it for writing. Please double check if no application is accessing it. You can also try removing the drive and plugging it back again, or dismounting it from the Partitions and Drives (or something along those lines) application.

**Comment by Addvilz** [comment]
I can confirm all of these issues - #96, #116 and #145 are caused by Windows Defender. How or why evades me, but so far I have tested on two distinct machines, both were facing the same error as in the linked issues, and both worked perfectly fine when I used workaround bellow.

A workaround is as follows:

1. Disconnect the USB device from the machine;
2. Reboot;
3. Open Windows Defender Security Center, then select Virus & threat protection > Threat settings;
4. Turn off Real-time protection;
5. Wait for a minute or so for the setting to catch up (this is Windows after all);
6. Run Media Writer as you normally would;
7. Detach the USB device (safely, of course);
8. Go back to Windows Defender Security Center, re-enable Real-time protection (same path as 3.).

**Comment by MartinBriza** [comment]
Hmm. Thanks for investigating, @Addvilz ! I'll see what I can do to avoid triggering this behavior. 

From the first glance, it seems you all may have stricter settings than me because the builds I have tested work just fine for me (I download them both from GitHub and getfedora.org - I don't use Windows to actually compile FMW.)

**Comment by Addvilz** [comment]
I tested 4.1.0 pre, 4.1.0 (default from Fedora download site) and 4.1.1. Both boxes I tested on had fresh clean installs of Windows done over the span of last week, with all defaults as is.

**Comment by ssandeep3** [comment]
Just 'off' the 'check apps and files' from windows defender security center for a moment...

**Comment by grulja** [comment]
I'm closing this now as this doesn't look like an issue in FMW. Feel free to re-open if you think otherwise.

**Comment by anton-x-t** [comment]
For me the fix was this for Windows
Run PowerShell as administrator
cd "C:\Program Files (x86)\Fedora Media Writer" (or other install path)
.\mediawriter.exe

**Comment by elliotclee** [comment]
I'm hitting this error now in Windows 11 while running FMW as administrator with Windows Defender 'Real-time protection' turned off. For comparison, on the same flash drive with the same ISO image, http://rufus.ie/ works fine.

**Comment by bbeaudoin** [comment]
Same issue with me. Windows 11 23H2, Fedora Media Writer was working with Fedora 37 and Fedora 38 but now it will erase the partitions on the USB drive then fail to write to the card. The Raspberry Pi Imager and Rufus 4.3.2090 still work fine. I upgraded to the November 7, 2023 release of Fedora Media Writer and it still isn't working as expected.

**Comment by djsolarix** [comment]
> Same issue with me. Windows 11 23H2, Fedora Media Writer was working with Fedora 37 and Fedora 38 but now it will erase the partitions on the USB drive then fail to write to the card. The Raspberry Pi Imager and Rufus 4.3.2090 still work fine. I upgraded to the November 7, 2023 release of Fedora Media Writer and it still isn't working as expected.

Turning off all Windows Defender's options worked for me.

**Comment by Devashish08** [comment]
any update how to solve this issue Destination drive is not writable. Couldn't open the driver for writing

**Comment by bbeaudoin** [comment]
If Raspberry Pi Imager and Rufus 4.3.2090, can't the Fedora Media Writer do the same thing to request the proper privileges? Disabling Windows Defender or using PowerShell as administrator seem to be workarounds, rather than a solution.

**Comment by beedell-roke** [comment]
@Addvilz, this might be tracked at [`issues/774#issuecomment-2508982276`](https://github.com/FedoraQt/MediaWriter/issues/774#issuecomment-2508982276), although a separate issue may remain warranted.
