### ISSUE TITLE
About the "Write to disk" button, is USB flash drive a "disk"?

### ISSUE THREAD

**Issue by sujiniku** [FedoraQt/MediaWriter#186]
There is a button "Write to disk"  But I think the shape of USB flash drive is not a disk but stick.
"Disk" in English is a circular object.

I think that "Write to Media" or "Write to Device" is better than "Write to Disk".

**Comment by mkilijanek** [comment]
Quick question about semantics: what is your partition manager in linux/windows/osx call your device? 
In my opinion this is semantics and it is deeply present in IT world to call "disk/hard disk/flash disk" device that stores data. 
In my opinion using "Write to Media/Device" is not precise enough. What media? What device? Device is also mouse, keyboard. 
"Disk" is present in IT nomenclature since first data storage disks showed up. I think we should avoid confusion with using more general terms like 'media/device'.

**Comment by MartinBriza** [comment]
Yeah, I don't think it's a huge issue. In case we go through a big UI overhaul, I think we can deal with stuff like this but changing a string just because of a tiny change in the meaning would break all our translations that'd have to be updated.
I say, it's not worth changing at the moment.
