### ISSUE TITLE
New Security Lab image is available

### ISSUE THREAD

**Issue by abitrolly** [FedoraQt/MediaWriter#187]
MediaWriter downloads `Fedora-Security-Live-x86_64-28-1.1.iso` on Fedora 28 while there is https://download.fedoraproject.org/pub/alt/releases/29/Labs/x86_64/iso/Fedora-Security-Live-x86_64-29-1.2.iso already available.

**Comment by TonyGprime** [comment]
Hi,
I'm new here and have been working my way around things and learning processes for only a short while and mostly on my own through sites like this and YouTube, 
Anyway, I'm stuck. I am running Windows 10 v.1803. I can't save anything to my internal hard drive. I have an external hard drive that I use. How do I configure Fedora Media Writer so that it will download the Distribution.ISO to my external hard drive. I don't see an option to change the download location. It seems to me that I've done this before, but I can't for the life of me remember for sure. 
Will someone please lend me a hand?

**Comment by MartinBriza** [comment]
@abitrolly This is something fedora-websites handles because the new release data is hosted at https://getfedora.org/releases.json Please open an issue here: https://pagure.io/fedora-websites/issues .

**Comment by MartinBriza** [comment]
@TonyGprime Sorry, the only way to do that is to change the Windows configuration to have your Downloads folder somewhere else. The path is taken from the system. If you want to have the ISO downloaded somewhere else manually, just download it yourself from getfedora.org. 
If you have any further questions, go ahead and ask in a new issue (there's a button for it in the upper right corner) or just send me an email to m@rtinbriza.cz

**Comment by abitrolly** [comment]
@MartinBriza worth documenting where the indexes are located at the top `README.md`?

**Comment by abitrolly** [comment]
https://pagure.io/fedora-websites/issue/905
