### ISSUE TITLE
imagewriter total mess , hanging. Fed 28/29

### ISSUE THREAD

**Issue by J-Dunn** [FedoraQt/MediaWriter#191]
Hi,

I have had issues with mediawriter hanging on Fed28 and gave up using it.  I'm now running Fed29 and hoped some progress may have been made, so I tried to burn the latest KDE spin to my Sandisk USBkey.

I had already downloaded the ISO image and checked the checksum, so I chose "custom image" and negivated to that iso image file.  It started OK so I left it to run ... 

When I came back a while later the window was completely locked and unresponsive and I remembered why I stopped using it before. I broke in with cntl-c and regained control. I removed the key and tried again. This time I let it go to find the iso on-line by itself. Same mess. 

While it was still working there was a message about it resizing the device. 

Now I find that the key is useless. dmesg shows it pulling in and recognises the device and even shows its serial no. However, nothing in /dev 

Previously it was showing as /dev/sdd ( I have 3 actual hard disks in this box ). 

I was expecting to use dd to rewrite the iso or reformat the device. But  how can I recover use of this device if I don't get a device number for it ?

**Comment by J-Dunn** [comment]
mediawriter 4.2.1 fc29 on Fed 29 LXDE spin

I tried to recover the device by rerunning. It completed download but having successfully downloaded the ISO it says no removable medium is present. Not surprising, since its just stuffed by hardware ! 

Windows do not update their content during download , only the progress bar and the text giving the bytes remaining get updated. 

If this is still in ALPHA development and likely to destroy folks hardware you should warn about this upfront. 

If there is a means to recover this USB key into a usable state where at least the kernel can recognise it and give it a device number please post how to do that. 
_

**Comment by MartinBriza** [comment]
FMW should not freeze when writing, this could be likely a graphics driver issue, which is beyond my control anyway. It is also possible that it froze because your flash drive died in the writing process. 

However, it is not possible that FMW _destroyed_ your device because there is a bug. All it does is opening the /dev/sdX device and dumping the iso contents in there. This is something you can do with `dd`, `cat` or you can even write stuff there directly with your favorite text editor. This accesses the memory cells and it is safeguarded by the OS, the USB controller and the controller inside the flash drive.

If your kernel sees the USB device and does not create a /dev/sdX file for it, it is pretty likely to be dead. If it however creates a /dev/sdX but no /dev/sdXY devices (where X is a letter and Y are numbers), it is still alive and you just need to create a new partition table - and FMW should offer you to do that when you plug the device in while FMW is running.

Flash drives die a lot, that's a fact. Flash memory is really error-prone and the more data you write to it, the bigger probability of it failing.

To reiterate, this is not a software bug, rather a hardware failure beyond my control. I'm open to answering more questions and go ahead and ask them but please calm down and keep a civil tone.

**Comment by J-Dunn** [comment]
Thanks for the reply Martin. 

> All it does is opening the /dev/sdX device and dumping the iso contents in there. 

It does more than "open the device". It starts by warning that it will resize the device and that this can be reverted later. Could you please explain all the steps it does and what low level commands it uses to achieve this on a linux system? 

There are some operations which should not be interrupted, I think. 

Having spent quite some time trying to recover the device I'm fairly convinced it has been bricked. 

I am aware of the write cycle limitations of flash technology but this device has had very little use.  I find the suggestion that it just chose that particular moment in time to go from fully functional device to total failure rather implausible. I do not like the idea of Linux destroying hardware and would like a better account of what may have gone wrong. It was a relatively low capacity device so the financial loss is not a problem but this tool is being pushed by Fedora as THE way to install in the installation notes. No mention of dd et co. 

Yes, I could have used dd, but have read that MW is supposed to be a more comprehensive solution for UEFI etc. and I wanted to see whether it worked any better than last time I tried it a couple of years ago ( when it also failed to update the screen and ended needing a kill -9 ).

**Comment by MartinBriza** [comment]
> It does more than "open the device". It starts by warning that it will resize the device and that this can be reverted later.

It does not literally resize the device, it just modifies the partition table so to the uninitated user it seems like the device is smaller but it really is not. 

> Could you please explain all the steps it does and what low level commands it uses to achieve this on a linux system?

You could achieve the same result by using dd if=/path/to/the/iso of=/dev/disk/by-id/usb-SOMETHING (this a symlink to /dev/sdX anyway). What FMW does is not opening the /dev file directly because you would need to be root to do that - it asks UDisks2 to open it over DBus by calling `org.freedesktop.UDisks2.Block.OpenForBenchmark` on its block device. OpenForBenchmark is used to be able to write and subsequently read the data to verify it had been written correctly - as OpenForRestore doesn't allow to read the data afterwards and vice versa for OpenForBackup (and calling these two consequently would require the user to enter their password twice).

> Yes, I could have used dd, but have read that MW is supposed to be a more comprehensive solution for UEFI etc. and I wanted to see whether it worked any better than last time I tried it a couple of years ago ( when it also failed to update the screen and ended needing a kill -9 ).

All of this is baked into the iso file already so there is no real need to NOT use dd, except FMW is more convenient and checks the written data.

> Having spent quite some time trying to recover the device I'm fairly convinced it has been bricked.

Bricked, broken, if you don't get a block device for it when you plug it in, it's just dead. I assume the same goes for windows and `diskpart` or their Drives and Partitions tool.

> It was a relatively low capacity device so the financial loss is not a problem but this tool is being pushed by Fedora as THE way to install in the installation notes. No mention of dd et co.

As I said, there is nothing FMW did wrong and there was no way to avoid it. I don't know how otherwise to convince you about the fact that there is no arcane magic cast upon your drive by using FMW instead of, say, dd.

> BTW, I tried to introduce a college to Fedora and MW failed on Windows too. I had to revert to a live boot and command line hacking using dd. A great account of how desktop ready Fedora is :(

I don't follow what you mean by this. Now note FMW does work a tad differently on Windows and Windows likes to mess around with drives connected to the system so it's pretty usual that when booting Fedora from a flash drive written using Windows, it's possible it'll fail the integrity test on bootup - however it doesn't affect the function if it passed the check in FMW.

**Comment by MartinBriza** [comment]
I'd also like to say this is just about the third report stating that FMW has broken the user's flash drive in the two years it has been used as an official way to get Fedora. Each day this repo gets >100 unique visits and it is not even pointed to by https://getfedora.org which is the place where most people get FMW. From this I assume there are probably tens of thousands of people who have used FMW in the past. To extrapolate the data, I must, regretfully, say you have probably just "won the lottery" and got a dead flash drive. Good news is if it's still under warranty, the manufacturer will likely replace it for you.

**Comment by J-Dunn** [comment]
Thanks for the detail on how it works.

> I don't know how otherwise to convince you about the fact that there is no arcane magic cast upon your drive by using FMW instead of, say, dd.

Well at least with dd it's direct and you know what happens. I have no idea what going via Dbus and using a benchmark tool to hack into the device implies but it sounds pretty archane to me. It sounds like what you do is an exploit of a badly designed dbus function which effectively short circuits the very foundation of Linux permissions and user control.  This means any userland software could effectively trash any hard-drive on the system if it wanted to, without the need for the root p/w.

I have no idea what stage it was at when it apparently locked up or whether it was still writing but the UI was just locked up. 

Yes most users don't have problems but then they use default Fedora and probably do the same things done when testing this in development. Bugs are often revealed by someone doing something a bit different from the average lambda user.  I suggest you try it on LXDE, The screen updating is totally borked, even it you just let it run and don't use the machine. Since Fedora pushed everyone into using nouveau I guess they wanted to know whether it produces any bugs. This may be one. Dead device aside there is a major UI disfunction here. 


Warranty, no, it's several years old. It's just that I don't carry it , it just sits on a shelf. Last time it got used was for installing Fedora 26, in view of the content I found before attempting to rewrite it. I have probably written to it half a dozen or a dozen times.

**Comment by MartinBriza** [comment]
> Well at least with dd it's direct and you know what happens. I have no idea what going via Dbus and using a benchmark tool to hack into the device implies but it sounds pretty archane to me. It sounds like what you do is an exploit of a badly designed dbus function which effectively short circuits the very foundation of Linux permissions and user control. This means any userland software could effectively trash any hard-drive on the system if it wanted to, without the need for the root p/w.

It asks for your password before you hit the write button, if you have not messed around with your polkit permissons. You still need privileged access but it depends on the access control settings on your system. I'm not hacking anything or circumventing anything. Yes, I'm using a function that's doesn't have the most descriptive name of all things but it's not a hack. It still goes through polkit and if nothing, it's more secure than requiring to run as root.

As per the driver issue, there's nothing I can do about it, there's no "don't blink with nouveau" switch in the Qt framework. The most I could do was to disable 3D acceleration so it doesn't crash as often...

**Comment by MartinBriza** [comment]
>>It asks for your password before you hit the write button, if you have not messed around with your polkit permissons.
>Phew! I think you forgot to mention that.

I thought it was obvious...

>Ah. so it's a know issue that there are driver problems. I've seen other projects moaning about nouveau. In principal it's a great idea but at this stage it's disappointing to see this many bugs. Yet another reason for using dd instead of GUI tools for this kind of job. The windozification of Linux becoming a serious problem.

WTF is windozification? It's starting to look like you're here just to complain and look for conspiracies left and right. I wrote FMW to make getting Fedora easier for people who don't understand computers all that well or don't want to mess around with creating a bootable flash drive all too much (which is the case especially in Windows) and want to try Fedora. Nobody is forcing using FMW instead of dd and dd is not going anywhere in favor of anything else.

>What do yo mean by "don't blink", do you have some idea what causes issues?

I meant flickering, my English is not as good as I wish sometimes. There are other issues with the graphcis drivers as a whole, though. And I'm not here to judge what is the cause, I'm just working with what I get.

**Comment by J-Dunn** [comment]
No conspiracies, just technology trends. There are attempts to unify and it tends to girate towards the larger mass : that is not in favour of Linux. I will probably open a bug about Fedora install instructions which only provide FMW instructions now. I went there looking for confirmation of exactly what I needed to feed to dd and found nothing. 

I'm not talking about flickering. There is a total lack of refresh of either the parent FMW window or its progress window on LXDE. The only thing which moves is the narrow line of the progress bar. Maybe that is a WM defect or an assumption that all WMs do the same thing as Gnome or KDE when this is not guaranteed  by freedesktop spec. 

Do you know what dbus is doing to resize ?  If it is trying to resize in a full safe way instead of just dumping on the disk label with a new partition is it possible it was doing a data preserving down size? This would be an enormous task on a drive with the previous Fedora iso and may have done enough ops to burn out the flash device. 

Could the way this happens depend upon the dbus / selinux settings of the spin?

**Comment by mkilijanek** [comment]
I think than you didn't read documentation for Fedora. It describes use of dd and gnome-disk-utility.
https://docs.fedoraproject.org/en-US/fedora/f29/install-guide/install/Preparing_for_Installation/#_writing_the_images_to_usb_media

If you are interested in dbus, then look for information there: https://www.freedesktop.org/wiki/Software/dbus/
and function used by FMW: http://storaged.org/doc/udisks2-api/2.6.4/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.OpenForBenchmark

> > It asks for your password before you hit the write button, if you have not messed around with your polkit permissons.

>Phew! I think you forgot to mention that.

**Comment by mkilijanek** [comment]
> Yes, effectively is seems that I missed the one line telling you how to use dd amid five pages tell you , you really , really want to use FMW. No, you really do !

Hmm, and what you expect? Printout from man pages for dd? Or just single line that allows you to write iso to USB drive? ;)

> Saying no to FWM seems like saying you don't want to be part of the EU: you just have not understood, you silly person, you need to chose again !!

What do you mean? You sound like there were no alternative to FMW, but there is. You can choose tool for Gnome, FMW or dd. Other tools, like those to make USB drive for Ubuntu, are not working - documentation discusses why and what kind of tools you can use to avoid similar problems. 

To be honest, I got impression, that you are complaining too much. You report issue with FMW, but it occurs your main complain is Linux itself and its implementation of DBUS. Again, this is not the place to do so - you should create issue for DBUS and discuss this with its developers.

>> Note that the file descriptor may be opened with the O_DIRECT and O_SYNC flags so care must be 
taken to only perform page-aligned I/O.

> What happens if one of these operations gets interrupted with a kill or device removal ?

To be honest, that is good question, but since this is module of DBUS, you should ask this question directly to them to get detailed answer.

In my opinion, you are reporting problem in wrong place. If you consider there is better solution than use of DBUS, then report proper change request ;)

**Comment by MartinBriza** [comment]
>>> Note that the file descriptor may be opened with the O_DIRECT and O_SYNC flags so care must be taken to only perform page-aligned I/O.

>> What happens if one of these operations gets interrupted with a kill or device removal ?

> To be honest, that is good question, but since this is module of DBUS, you should ask this question directly to them to get detailed answer.

> In my opinion, you are reporting problem in wrong place. If you consider there is better solution than use of DBUS, then report proper change request ;)

The FD returned from UDisks will get closed and on the next write() call no bytes will get written. Writing ends with a failure and an error message gets displayed....

**Comment by J-Dunn** [comment]
mkilijanek 
> To be honest, that is good question, but since this is module of DBUS, you should ask this question directly to them to get detailed answer.

To be honest anyone using this should have asked themselves the same question and should know the answer. 

  MartinBriza , thanks.  I was more meaning what would the result be for the device. But thanks for the reply. I recall several years ago a problem where a failed write to a ( possibly defective ) hard disk drive was hanging Linux. Some with relevant knowledge explained to me that certain low level ops were just assumed to work and never timed out since having timeout timer would make them slower.  There was an implicit assumption that the hardware worked flawlessly. That may no longer be the case. In today's world of multicore CPUs it would presumably only hang one core. IIRC on my simgle core AMD at the time it just locked up and I needed to power cycle the computer. 

Dead device aside, there is serious UI bug here, at least on LXDE possibly in conjunction with nouveau drivers but since it seems easier to write this off as a freak h'w failure, a conspiracy nut user who has been messing with his selinux settings, than to even accept and investigate the possibility of a bug, I'm out of here.

**Comment by MartinBriza** [comment]
> MartinBriza , thanks. I was more meaning what would the result be for the device. But thanks for the reply. I recall several years ago a problem where a failed write to a ( possibly defective ) hard disk drive was hanging Linux. Some with relevant knowledge explained to me that certain low level ops were just assumed to work and never timed out since having timeout timer would make them slower. There was an implicit assumption that the hardware worked flawlessly. That may no longer be the case. In today's world of multicore CPUs it would presumably only hang one core. IIRC on my simgle core AMD at the time it just locked up and I needed to power cycle the computer.

The result is exactly the same as the result of unplugging your flash drive while you're copying files to it with cp or any other tool. To understand this further, I recommend reading up on how do partition tables and file systems work. This article for example does go in a good deal of details on filesystems: https://www.tldp.org/LDP/sag/html/filesystems.html

I don't think there is any UI bug and the SELinux stuff you guys are talking about is completely unrelated to anything we discussed before.

**Comment by MartinBriza** [comment]
@mkilijanek also, your problem was something else btw: writing to your flash drive got interrupted very soon, so maybe even the partition table got broken, so you couldn't see any partitions - but this is fixed easily: by just creating a new partition table. meanwhile @J-Dunn 's issue is a completely dead flash drive (no /dev/sdX device gets created on plugging in) where cannot access the memory cells at all anymore

this is different because the partition table is contained right at the "start" of the memory "strip" that is the actual memory of the flash drive - but now i'm delving into how drive partitioning work and i hope you guys will do your own research on this topic yourselves if you're interested
