### ISSUE TITLE
[RFE] Add intructions how to use MediaWriter to the main view

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#195]
When you launch Fedora Media Writer, it looks like this:

![image](https://user-images.githubusercontent.com/213068/54218952-6c339f00-44e6-11e9-9f78-3d1bc6130a13.png)

My feeling is that the list is missing a bit of context. What is it? What's happening here?

It would be good to add some information which explains how the media writer works and what the list is for. For example:

"Create a bootable USB drive to run Fedora live or install it on your computer. To start, connect the drive you want to use and select which version of Fedora you want to use.

For more information, see the [Fedora installation guide](https://docs.fedoraproject.org/en-US/fedora/rawhide/install-guide/)."

What do you think, @jimmac?

**Comment by MartinBriza** [comment]
Hey Allan,
thanks for revisiting the FMW design. I'm looking forward to any remarks you and @jimmac have or will have in the future. 
When I have a minute, I'll start by fixing the other clearer issues you've highlighted in the other reports and I'll follow up on this one (or any future ones). I agree it can definitely be improved but as I'm not a designer myself, I didn't venture too far from the initial mockups into changing stuff around the app.
Just one thing to take into consideration: since this app is not actually written using GTK and it needs to work in all three major desktop platforms, I would very much like to steer away from using header bars.

**Comment by allanday** [comment]
I think we can probably drop this.
