### ISSUE TITLE
[Need Clarification] When can we expect the next release? 

### ISSUE THREAD

**Issue by cyfrost** [FedoraQt/MediaWriter#199]
Just curious if there's a release being planned :)

**Comment by MartinBriza** [comment]
At some point in April, hopefully. There's a chance I'll manage to get it out this (Apr 15) week. 
We got some pretty important fixes in and now we're stuck on figuring out what to do with the release process on the Fedora side because it's been a while since the last one (as I'm not actually the person to do the releases for getfedora.org).
Hit me up if you have any followup questions!
