### ISSUE TITLE
Please tell me, is this normal behavior? USB device no longer detected

### ISSUE THREAD

**Issue by Jon-guy30** [FedoraQt/MediaWriter#201]
So I downloaded the Fedora KDE spin (manually) because I'm interested in trying out Wayland. But when I wrote the ISO to the USB drive it became undetectable. Now, this isn't an issue since it's easily fixed using Microsoft Diskpart utility. At first I thought it was because it already had an ISO in it, turns out that wasn't the case. I used diskpart to make it detectable again and I rewrote the ISO, same thing happened again. In disk management it shows that it only has a single 100 megabyte partition and a huge unallocated space. It also doesn't show up in Explorer. 

I want to use this tool because it has the verification feature, I searched the web for a bit for this problem and I couldn't find anything. I did find a video on YT and in the video it worked as I would expect it to. 

Other USB writers always let me browse the files using Explorer, why not Fedora Media Writer?

The device is a Kingston DataTraveler G4 8gb.

I'm confused??

**Comment by MartinBriza** [comment]
Hey, sorry for taking this long to reply.
First, to fix this issue, start Fedora Media Writer and insert the flash drive in question. It should show an option to restore the flash drive for you to be able to use it normally again. You can also fix this by using `diskpart`, I think the command to fix this is `select disk X` where `X` stands for the disk number of the flash drive and then `clear`. Then you can create partitions as you were used to.
This is caused by the fact we're copying the ISO to the flash drive bit-for-bit, which means it will have the same partition layout as the ISO file did. It is in a special format that allows it to boot on various systems from both USB and CDs, which in turns means some OSes will detect the partition layout wrong when the system is still online - what matters is BIOS/UEFI is able to read it and boot from it though.
Please feel free to ask any followup questions, I'm not sure if I worded it completely comprehensibly.

**Comment by Jon-guy30** [comment]
I see, interesting. Did it always work that way though? I looked at an older video demonstration of FMW and it showed up in explorer. And yes, I know how to fix a bad drive. :)

Thanks for the response, don't worry, I'm patient. ;)

**Comment by MartinBriza** [comment]
I think at some point I added code that prevents mounting the drive after writing because it breaks the MD5 checksum calculation when booting from the drive - Windows tends to create the "System Volume Information" folder on every single mounted partition which changes the contents of the drive (thus changing its final MD5 sum). That may be the reason the system doesn't mount it.

However, even if Windows sees "the partition", it actually only sees a small portion of the drive, about 10MB from what I recall. Again, this is due to the "hacks" that are used to be able to boot the drive on every system.

**Comment by MartinBriza** [comment]
And sorry for including the instructions, the "fixing the drive" part is not as obvious as it should be - for example in the default Windows Formatting Tool, you can only see the 10MB partition I mentioned before. And in the "Volumes and Partitions" (or whatever is it called) tool, you can't re-format and clear the drive correctly, too, because USB drives use 512B blocks normally, but from the partition table this tool thinks the blocks are actually 2048B long - and this breaks it when working with the flash drive that contains a FMW-written Fedora image.
