### ISSUE TITLE
Windows Release Binary: Trojan Detected

### ISSUE THREAD

**Issue by najik** [FedoraQt/MediaWriter#202]
<img width="901" alt="2019-05-18_155651" src="https://user-images.githubusercontent.com/3673600/57975788-f2a8a900-798d-11e9-8807-fc18ca8af269.png">

RedHat Docs on Media Creation:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/sect-making-usb-media

Link to GitHub Repo:
https://github.com/MartinBriza/MediaWriter/releases

Redirects to:
https://github.com/FedoraQt/MediaWriter/releases

Downloaded and installed the following file:
https://github.com/FedoraQt/MediaWriter/releases/download/4.1.4/FedoraMediaWriter-win32-4.1.4.exe
md5sum:
    e4a53325cad6811b818d65504bc091b5  FedoraMediaWriter-win32-4.1.4.exe
sha256sum:
    0123e04142ad72a63f416906284fc21f1258854bea0b41df5a3e16b324ec99b4  FedoraMediaWriter-win32-4.1.4.exe

Trojan:Win32/Bearfoos.A!ml

Alert level: Severe
Status: Quarantined
Date: 5/18/2019

Recommended action: Remove threat now.
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items:
    file: C:\Program Files (x86)\Fedora Media Writer\helper.exe
    
    process: pid:1208,ProcessStart:132026896571619897
    
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fBearfoos.A!ml&threatid=2147731250

VirusTotal report for helper.exe:
    https://www.virustotal.com/#/file/86a7e10e70732937616f958aa839ac6dfbf025cd4adc977d88dedb06ff6baf3e/detection

**Comment by MartinBriza** [comment]
Thanks for reaching out about this. This is pretty serious, because I'm fairly certain there is a very slim chance the Windows release contains any sort of a virus. I'm building the Windows releases in a Fedora VM using the MinGW packages without touching real Windows at all. The only way this could be contaminated would be if the MinGW packages were containing any kind of malicious code.
Therefore, I'm convinced this is a false positive. I'll try it on my Windows machine and reach out to Microsoft (or somebody else?) to confirm it is so.

**Comment by grulja** [comment]
Windows installer is now being built in Github CI or by Fedora release engeneering so it should no longer be an issue.
