### ISSUE TITLE
Leave larger FAT16 partition

### ISSUE THREAD

**Issue by abitrolly** [FedoraQt/MediaWriter#241]
I tried to backup BIOS using Fedora USB stick and the file became corrupted, because FAT16 partition is only 12Mb in size with 479.2 kB free.

I would help a lot with BIOS upgrades if FAT16 partition was larger by few tens of megabytes. 100Mb should be enough for everybody.

**Comment by abitrolly** [comment]
The partition table is very strange. Is it two primary partitions inside of the big one?

```bash
$ sudo fdisk -l /dev/sdc
Disk /dev/sdc: 7.51 GiB, 8053063680 bytes, 15728640 sectors
Disk model: UDisk           
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2ebdc43a

Device     Boot Start     End Sectors  Size Id Type
/dev/sdc1  *        0 3840191 3840192  1.9G  0 Empty
/dev/sdc2         172   22559   22388   11M ef EFI (FAT-12/16/32)
/dev/sdc3       22560   69423   46864 22.9M  0 Empty
```

**Comment by MartinBriza** [comment]
This is not a Fedora Media Writer bug but actually the way how Fedora ISOs are composed. I will close this bug because I can't really do anything about it (we're using Fedora ISOs as-is, without modifying anything at all).

Explanation: To be able to boot from any media on any computer, Fedora ISOs are composed in a very special partition layout with a specifically crafted boot loader in the start of the image that allows it to boot from "floopy disks", CDs or from USB while maintaining compatibility with regular PC and Mac computers that have varying filesystem support. Overall, it's a really complex system and the flash drive will seem to have completely different partition layout on all Windows, MacOS and Linux systems. This is called `isohybrid`, you can read more about it here: https://wiki.syslinux.org/wiki/index.php?title=Isohybrid .

**Comment by abitrolly** [comment]
@MartinBriza the Fedora Media Writer is the entrypoint. Who builds those hybrid image then? Where to address this issue?

**Comment by abitrolly** [comment]
Following https://wiki.debian.org/ManipulatingISOs I found https://manpages.debian.org/buster/xorriso/xorriso.1.en.html which allows to modify ISOs in different ways. Would be nice to understand how this FAT16 partition is mapped into ISO. Is it a specific file that can be resized, or just a carefully carved continuous block of free space.

On the other hand, it is possible to use https://www.ventoy.net/en/index.html as an alternative for a practical version of USB drive.
