### ISSUE TITLE
Install error on Debian 10: "requires the runtime org.kde.Platform/x86_64/5.14"

### ISSUE THREAD

**Issue by nikolas** [FedoraQt/MediaWriter#259]
Hello,
I just installed Flatpak on my Debian 10 system, and I'm having trouble installing Fedora Media Writer:
```
$ flatpak install org.fedoraproject.MediaWriter-4.1.6.flatpak
error: The application org.fedoraproject.MediaWriter/x86_64/master requires the runtime org.kde.Platform/x86_64/5.14 which was not found
```

Do I need to manually install some KDE dependencies or something? I'm not using any desktop environment - just xmonad.

**Comment by nikolas** [comment]
Well, I ended up just writing the Fedora iso to my usb drive with dd. `dd` doesn't require KDE >_<

**Comment by dreua** [comment]
I think this is more a flatpak issue than a MediaWriter issue. I've seen this before, I think you need to manualy install the dependencies because you are installing from a local file, have you tried [getting it directly from flathub](https://flathub.org/apps/details/org.fedoraproject.MediaWriter)?
`flatpak install flathub org.fedoraproject.MediaWriter`

**Comment by grulja** [comment]
Either get MediaWriter directly from Flathub or download the KDE runtime from there.
