### ISSUE TITLE
Signing windows binaries.

### ISSUE THREAD

**Issue by humaton** [FedoraQt/MediaWriter#265]
Hi, I am trying to sign windows binaries so we can distribute them to windows users https://pagure.io/releng/issue/9577.
I have had trouble building the project using your build script in dist/win. 

Could you please update documentation on how cross-compile your project on the latest Fedora?

I have stumbled on a couple of issues some I was able to overcome but I am lost with this one:

``` 
=== Composing installer
+ unix2dos
++ du -k -d0 /home/thrcka/projects/MediaWriter/build/app/release
++ cut -f1
+ INSTALLED_SIZE=103284
+ cp /home/thrcka/projects/MediaWriter/dist/win/mediawriter.nsi /home/thrcka/projects/MediaWriter/dist/win/mediawriter.tmp.nsi
+ sed -i 's/#!define VERSIONMAJOR/!define VERSIONMAJOR 4/' /home/thrcka/projects/MediaWriter/dist/win/mediawriter.tmp.nsi
+ sed -i 's/#!define VERSIONMINOR/!define VERSIONMINOR 1/' /home/thrcka/projects/MediaWriter/dist/win/mediawriter.tmp.nsi
+ sed -i 's/#!define VERSIONBUILD/!define VERSIONBUILD 4/' /home/thrcka/projects/MediaWriter/dist/win/mediawriter.tmp.nsi
+ sed -i 's/#!define INSTALLSIZE/!define INSTALLSIZE 103284/' /home/thrcka/projects/MediaWriter/dist/win/mediawriter.tmp.nsi
+ makensis -DCERTPATH=/home/thrcka/projects/ -DCERTPASS=/home/thrcka/projects//authenticode.pass /home/thrcka/projects/MediaWriter/dist/win/mediawriter.tmp.nsi
sh: tempinstaller.exe: command not found
!system: returned 32512, aborting
Error in script "/home/thrcka/projects/MediaWriter/dist/win/mediawriter.tmp.nsi" on line 38 -- aborting creation process
```

**Comment by MartinBriza** [comment]
Hi, I don't have a Windows signing certificate (and I didn't for a very long time). In this case, I assume the issue is somewhere in the generation of the uninstaller in `nsis`. A wild guess in this case would be that the uninstaller doesn't get signed/generated at all inside the first run of installer generation but I really can't prove that in any way.

Just to clarify: The uninstaller is generated and signed like this:
* A mock installer gets created
* The mock installer gets ran inside `wine`, that installs (an unsigned) uninstaller
* The uninstaller gets signed
* A real installer gets created, with the uninstaller injected from the previous steps.

Hopefully this will help you with the investigation.

**Comment by humaton** [comment]
Thanks for the reply. Strange for me is that the build process is complaining about the file that generated and cleary is in the build directory.

**Comment by humaton** [comment]
I am not sure how to continue here. The nsi file make the temp.exe executable on line https://github.com/FedoraQt/MediaWriter/blob/master/dist/win/mediawriter.nsi#L37
but it fails to execute it on the next line. I have tried to build this in a fresh VM with f32 without any success.

**Comment by grulja** [comment]
I think this can be closed. We are already able to sign binaries.
