### ISSUE TITLE
[RFE] Add option to change language

### ISSUE THREAD

**Issue by nicki419** [FedoraQt/MediaWriter#271]
My Windows Language is English (US), my default app language is English (US) but my region is set to Germany, and so are date and time formats. For some reasons, many programs, including Fedora Media Writer think it's appropriate to ignore Windows and APP languages and orientate on region settings. I didn't set my language to Enlgish (US) to use all my apps in German.

Please change that.

**Comment by rasmuoy** [comment]
I have same issue, Norwegian keyboard, and Norwegian region settings - however OS language and every relevant setting this app should care about is set to English. It's extremely frustrating to work with a Norwegian application when it has no reason to do so.

Please follow a sane standard and use system language and not region settings for language settings.

**Comment by teetow** [comment]
Same issue. The Swedish word-for-word translation is so bad I didn't dare to use it, the options are all completely incomprehensible. This is not a feature request, it's a legit bug. 

Steps to reproduce:

* Set Windows system language to English
* Select Swedish for regional info (numbers and dates)
* Bug happens

Check this comment for some digging I did when Musescore fell into the same Qt problem:

https://github.com/musescore/MuseScore/issues/13926#issuecomment-1288156521

From my understanding, you want either `QLocale.system().language()` or `QLocale.system().name()`, not whatever `QLocalesystem0.uiLanguages0` is.

**Comment by grulja** [comment]
> Same issue. The Swedish word-for-word translation is so bad I didn't dare to use it, the options are all completely incomprehensible. This is not a feature request, it's a legit bug.
> 

You can try to suggest better translation here https://translate.fedoraproject.org/projects/fedora-media-writer/.

**Comment by teetow** [comment]
Very few Swedes need (or indeed want) localization, especially for a technical tool like this. It just increases the cognitive tax of using it, as there are few established terms for things like "release" and whatever the hell "utgåva" is meant to translate. I think it would be prudent to respect that localization is only useful for certain users, to others it's a hindrance. Following the system language is how everyone gets what they want.

Frankly, if the bug is fixed, it won't matter how bad the translation is. Did you look into the information I provided? Is it applicable?

**Comment by teetow** [comment]
As an example, the established Swedish translation for "release" is... "release."

**Comment by rasmuoy** [comment]
I strongly agree with @teetow here. This is not a feature request for allowing a change of language, it is a bug report asking for the app to respect the choice already made.

Why is it looking at time and currency format to select the language? It makes no sense, and they are not the same.

Time and currency format is there to say I want my dates to be dd.mm.yyyy instead of mm.dd.yyyy and for commas to be the decimal marker instead of periods. It is completely unrelated to language.

The app should obviously follow the system language, as in the language we have selected to be displayed on our system.

This should hopefully be a very minor fix, but helps people in our situation a lot.

**Comment by rd77g** [comment]
just downloaded win64-5.2.3 version and still autotranslates to locale language instead of UI language. Windows (and every application I do install) are set to English although my locale is not. The installer is in English but the main application is not.

I also tried a clean install from  https://github.com/FedoraQt/MediaWriter/actions/runs/11952903378 just in case but same result
