### ISSUE TITLE
USB disk once created is not editable windows 10

### ISSUE THREAD

**Issue by balasubramanyamsivaneni** [FedoraQt/MediaWriter#282]
hi all,
i have downloaded FMW 4.2.1 and able to create LIVE USB (16GB) using the custom built RHEL 8.2 DVD.
To use this USB on one of our appliances to boot RHEL8.2, we need to change the "ks=cdrom/ks.cfg" with "ks=hd:sdb1:/ks.cfg"
in the grub.cfg and isolinux.cfg .
but we dont see the USB drive detectable my windows . somehow we got it detected on MAC, but unable to edit.
please advice

thanks

**Comment by dreua** [comment]
The purpose of this tool is to create USB disks that can install Linux on your computer, not USB drives that are readable by Windows. I think it works as advertised and you are asking the wrong question in the wrong place.

**Comment by balasubramanyamsivaneni** [comment]
thanks for the response. 
This was working with FMW 3.12.0. where we could create the USB disk using RHEL7 ISO, edit the grub.cfg to "ks=hd:sdb1:/ks.cfg" and install rhel OS successfully on appliances. 
we used the same FMW 3.12.0 to create USB disk using RHEL8 ISO. this one fails installing OS .
so we started using FMW 4.2.1 and are stuck at unable to edit the grub.cfg.
any pointers or help will unblock us.

thnaks

**Comment by MartinBriza** [comment]
This is not caused by FMW but the format of the iso images.There's a very
special partition table and following partitions that allow them to be
booted from CDs, USB devices, etc. on a broad spectrum of devices. It's not
intended for being modified or even read from a running OS. You may be able
to modify the GRUB config from a running Linux system but I don't recommend
doing so because you may break another part of this partition layout.

If things didn't change since I was working with this, the image format is
called isohybrid: https://wiki.syslinux.org/wiki/index.php?title=Isohybrid
. I recommend reading this page and/or investigating the process how RHEL
images are built. I think you may be able to "unpack" the isohybrid image,
modify it and pack it again. However, as mentioned, I've not done that
before and it's completely unrelated to Mediawriter.

**Comment by balasubramanyamsivaneni** [comment]
Thank you MartinBriza.
