### ISSUE TITLE
helper.exe runs in bg and stops from FMW reinstall on Win10

### ISSUE THREAD

**Issue by sumantro93** [FedoraQt/MediaWriter#483]
I installed the new FMW exe on win10. 
Uninstalled the app. 
Redownloaded the new exe
When I try to install there is a error... which is https://imgur.com/a/iqQZcjh

With a lil bit of debug, found out that C://Program Files(x86) has a Folder named "Fedora Media Writer"
when I try to ctrl+shift+del it tells me there is a bg process running.
On my process manager is a "helper.exe" which keeps running and when I kill it, then only the Folder gets deleted
This is the only way, I am able to reinstall FMW on win10.

This violates, the uninstall completely functionality and should be a blocker as it doesn't also help with reinstalling by the user.

**Comment by kparal** [comment]
Attaching the image directly here:
![e8V98o2](https://user-images.githubusercontent.com/755451/167150336-7d67106f-6751-4d4c-92bb-e2b9fe5d923a.png)

**Comment by kparal** [comment]
In general I can uninstall and reinstall FMW just fine, without issue. BUT, I saw this once as well. When this happened, it was because mediawriter.exe process was hanging for some reason (I think I tried to start it and the window didn't come up). Windows allowed me to uninstall it, even though it was hanging, and the error happened only during next install, when it couldn't overwrite the files, exactly as in the screenshot.

It's definitely a problem that mediawriter.exe can get hanging sometimes, but this actual problem with reinstall is rather a problem/poor functionality of Windows, I think.

**Comment by sumantro93** [comment]
In my case, this is the 3rd time I am trying it happens each and every time for me.

**Comment by grulja** [comment]
I haven't seen this issue, but anyway it's most likely not a new issue introduced in the new FMW.

**Comment by kparal** [comment]
@sumantro93 There's a new Windows build up, can you please test it?

**Comment by sumantro93** [comment]
> @sumantro93 There's a new Windows build up, can you please test it?

Done, with windows 11 and windows 10 its fixed.
