### ISSUE TITLE
Fedora rawhide be in the menu?

### ISSUE THREAD

**Issue by romulasry** [FedoraQt/MediaWriter#587]
Good idea?

**Comment by grulja** [comment]
> Good idea?

I don't really think so. I believe FMW is used by many newcomers and not all of them will have clue what is rawhide. We don't want new users to install rawhide instead of a stable release and have a bad experience. I also don't think many people download rawhide image and install it that way. Most likely they test rawhide images in a VM or they upgrade from their stable release.
