### ISSUE TITLE
Fedora MediaWriter made usb drive unusable

### ISSUE THREAD

**Issue by DilanRona** [FedoraQt/MediaWriter#626]
As stated in the title, I used media writer to write Fedora Gaming to a USB. USB would not boot after I tried it, initial searching said the issue was most usb drives are formatted for NTFS, and not FAT32. So I inserted the stick into a windows machine the next day, getting ready to format the drive.

Drive is completely unusable now, and its a brand new usb that was never used before. Windows cannot detect a volume. So I tried Gnome-Disks, fdisk, parted, and diskpart on windows in an effort to fix the usb, and they all failed. Error messages in all cases boils down to a "no volume in selected disk". Cannot clear the disk, cannot create any partitions, nothing.

**Comment by grulja** [comment]
You should be able to recover your USB drive using Fedora Media Writer. It should detect there is a Fedora image on it and offer you to restore your drive. In order to recover your drive using other tools, I believe you will have to write a new partition table.

**Comment by DilanRona** [comment]
Tried to recover it with media writer. Only options it showed is Download iso, and select iso. No option to restore or repair. Every other tool for Linux and Windows cannot detect any volume, and will not allow the creation of new volumes or partitions.

**Comment by grulja** [comment]
Try to write a yet another Fedora image on it and when going back to the main menu, there should be option to recover your drive. Where did you write your image? Was it on Windows or on Linux? 

Try to use e.g. GParted and when selecting the drive, go to Device > Create Partition Table.

**Comment by DilanRona** [comment]
Image was written from Fedora 38. Mediawriter cannot pick up the usb at all, regardless how many times I tried. Verified that its in the dev directory, and it does show up as /dev/sdb in my case. But cannot select the usb from Mediawriter.

GParted doesnt list the drive either. When I start it from the command line, passing /dev/sdb it throws out an error, and will not go further.

**Comment by grulja** [comment]
I'm afraid that your drive is probably damaged, but I  don't think FMW is responsible for that as on Linux we are writing the same way as you would do `dd if=path/image_name.iso of=device` command that is being used for years. I just tried to write a Fedora Games image on an USB drive and it works just fine, I can see an option to recover my drive in FMW.

What does `sudo fdisk -l` says?

**Comment by grulja** [comment]
Ping? Have you been able to recover your drive or not?

**Comment by thunderpants** [comment]
I had the same problem after installing Fedora Atomic iso while on PopOS.
I got my usb back though i can't remember what did it or if it just bugged out and cleared the partitions.
I do remember using GParted on Zorin 17.1  to delete the partitions though there an error warning . But when i booted up win10 and checked it on Disk Management it was empty ,no partitions at all and i quickly made a new 64gb NTFS partition .

Reminds me of balenaEtcher when it first appeared on the scene . That was doing similar stuff to usb drives.
Totally killed one of my usbs ,though it has improved a lot since then.

**Comment by DilanRona** [comment]
wasnt able to recover that usb, cant even format it on windows, or linux using the standard format tools. And I even tried removing and creating partitions. Failed.
    On Tuesday 29 August 2023 at 13:40:23 GMT+2, Jan Grulich ***@***.***> wrote:  
 
 


Ping? Have you been able to recover your drive or not?

**Comment by dwarez** [comment]
Do a favor to the community and make this failed project deprecated. It just made my 128GB usb drive unusable after crashing during the restore operation.

Do yourself a favor and never use this abomination of software.

**Comment by grulja** [comment]
> Do a favor to the community and make this failed project deprecated. It just made my 128GB usb drive unusable after crashing during the restore operation.
> 
> Do yourself a favor and never use this abomination of software.

I'm sorry to hear that, but I don't think a failure in the middle of drive restoration makes it unusable. You can still use other tools to properly restore it or write a Fedora image again onto your drive and have it restored again using FMW.

**Comment by tinyflower108** [comment]
Same issue here, Fedora Media Writer just bricked 2 separate new USB drives, they are now undetectable by FMW (no way to restore them) as well as any other program. I think instead of dismissing multiple people who report the same bug it would be better to investigate the issue.

**Comment by grulja** [comment]
Hi, I have never encountered an issue where FMW would made an USB drive bricked, it always restored my drives properly using FMW and therefore I didn't go to fix it as I could not reproduce it. In any case, I believe when FMW fails to detect an USB drives in order to restore it, there is always [Rufus](https://rufus.ie/en/) tool that will for sure restore your drives successfully. FMW uses only Windows API to manipulate with USB drives and for that reason I don't think it can do any operation that would lead to damaging them.

**Comment by DilanRona** [comment]
Even Rufus couldn't fix that drive that FMW bricked somehow. At this stage, with the amount of bug reports that are coming through, and not resolved, I don't think it's safe to use.
    On Monday 4 August 2025 at 08:09:07 GMT+2, Jan Grulich ***@***.***> wrote:  
 
 grulja left a comment (FedoraQt/MediaWriter#626)
Hi, I have never encountered an issue where FMW would made an USB drive bricked, it always restored my drives properly using FMW and therefore I didn't go to fix it as I could not reproduce it. In any case, I believe when FMW fails to detect an USB drives in order to restore it, there is always Rufus tool that will for sure restore your drives successfully. FMW uses only Windows API to manipulate with USB drives and for that reason I don't think it can do any operation that would lead to damaging them.

**Comment by grulja** [comment]
I still believe FMW cannot do any operation that would lead to bricking an USB drive. It does perform similar to Balena Etcher (mentioned here before) and Rufus. See https://blog.balena.io/did-etcher-break-my-usb-sd-card/.

And even these tools have similar issues reported, like https://github.com/balena-io/etcher/issues/4399 or https://github.com/balena-io/etcher/issues/4218 or https://github.com/pbatard/rufus/issues/313. I'm not saying this justifies the issue you encountered with FMW, just that it is not clear that the FMW is here to blame.

**Comment by grulja** [comment]
Also based on https://tooomm.github.io/github-release-stats/?username=FedoraQt&repository=MediaWriter, it looks FMW on Windows has hundreds of thousands downloads. If it was a common issue that FMW bricks USB devices, there would be more than few reports. I wish to be able to investigate this issue, but it has never been reproducible on my end and I'm sure I have broken a record in number of images one can write during a short period when I was rewriting this write/restore funcionality last year.

**Comment by tinyflower108** [comment]
I have been able to repair the drive, it didn't show up as a drive in any system, nor as a repair option BUT when i chose to write an image it suddenly showed up again, so it seems to be an issue where the drive becomes undiscoverable if writing to it fails

**Comment by Daeltam** [comment]
I tried to Install Raspberry Pi OS with FMW on a Micro SD card, didn't work, now I can't find a way to restore it.
No button appears, SD Card Formatter says it's Read-Only, FMW doesn't want to overwrite with another iso ("Read-only" file). 

Just tried on Rufus using a windows machine : Error C003045D, hardware error, it doesn't work either.

I am using FMW on Fedora KDE Plasma 42.

This seems like a recurrent problem and a serious one, sticks and cards aren't free...

**Comment by ianmllr** [comment]
> Also based on https://tooomm.github.io/github-release-stats/?username=FedoraQt&repository=MediaWriter, it looks FMW on Windows has hundreds of thousands downloads. If it was a common issue that FMW bricks USB devices, there would be more than few reports. I wish to be able to investigate this issue, but it has never been reproducible on my end and I'm sure I have broken a record in number of images one can write during a short period when I was rewriting this write/restore funcionality last year.

Outright dismissing an error that hundreds of people are reporting is.. a choice. It just happened to me as well.  From what I can tell in this thread, it seems like it happens when using FMV on Linux. I have used this USB stick exactly two times: once on Windows to install Fedora KDE Plasma which went fine, and once to put Fedora Workstation on it (from Fedora KDE Plasma). Now, it's bricked.

**Comment by grulja** [comment]
> Outright dismissing an error that hundreds of people are reporting is.. a choice. It just happened to me as well. From what I can tell in this thread, it seems like it happens when using FMV on Linux. I have used this USB stick exactly two times: once on Windows to install Fedora KDE Plasma which went fine, and once to put Fedora Workstation on it (from Fedora KDE Plasma). Now, it's bricked.

Hi, there are not hundreds of reports, I can count reports in this bug on my hands. Anyway, I'm not saying there is not a possible problem, I have just not been able to reproduce it. It has been also mostly reported on Windows, as on Linux the behavior of FMW is not different from the usual `dd` command. I believe you should be able to restore your USB drive using `kpartitionmanager` on KDE Plasma or `gparted` on Workstation.

**Comment by ianmllr** [comment]
> > Outright dismissing an error that hundreds of people are reporting is.. a choice. It just happened to me as well. From what I can tell in this thread, it seems like it happens when using FMV on Linux. I have used this USB stick exactly two times: once on Windows to install Fedora KDE Plasma which went fine, and once to put Fedora Workstation on it (from Fedora KDE Plasma). Now, it's bricked.
> 
> Hi, there are not hundreds of reports, I can count reports in this bug on my hands. Anyway, I'm not saying there is not a possible problem, I have just not been able to reproduce it. It has been also mostly reported on Windows, as on Linux the behavior of FMW is not different from the usual `dd` command. I believe you should be able to restore your USB drive using `kpartitionmanager` on KDE Plasma or `gparted` on Workstation.

Neither GParted, KDE Partition Manager or Rufus can get it back. It will say "scanning device" for about a minute, then I get notified that the stick has been disconnected.

**Comment by grulja** [comment]
> Neither GParted, KDE Partition Manager or Rufus can get it back. It will say "scanning device" for about a minute, then I get notified that the stick has been disconnected.

Hmm, it might be indeed dead, but still the FMW writes images the same way as other tools so I still think it's not FMW fault. What kind of USB stick it was? Was it possibly some cheap USB device?

**Comment by grulja** [comment]
@ianmllr can you open a terminal, run `sudo dmesg -w` and plug in your USB drive to see what it reports and if there is any failure?

**Comment by ianmllr** [comment]
> > Neither GParted, KDE Partition Manager or Rufus can get it back. It will say "scanning device" for about a minute, then I get notified that the stick has been disconnected.
> 
> Hmm, it might be indeed dead, but still the FMW writes images the same way as other tools so I still think it's not FMW fault. What kind of USB stick it was? Was it possibly some cheap USB device?

I can only be FMV's fault, it is the only thing I have ever used the stick for. As I said, once to put Fedora KDE on there and once from Fedora KDE to put Fedora Workstation on there. It wasn't a cheap $1 stick from Alibaba, it was a regular $9 one from the local tech store

[29434.506222] usb 2-3: new SuperSpeed USB device number 33 using xhci_hcd
[29434.519066] usb 2-3: New USB device found, idVendor=0808, idProduct=0909, bcdDevice=ff.ff
[29434.519073] usb 2-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[29434.519074] usb 2-3: Product: USB300U3
[29434.519075] usb 2-3: Manufacturer: USB3USBC
[29434.520850] usb-storage 2-3:1.0: USB Mass Storage device detected
[29434.521149] scsi host0: usb-storage 2-3:1.0
[29435.096703] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.RP09.PEGP.NVDN], AE_NOT_FOUND (20250807/psargs-332)
[29435.096722] ACPI Error: Aborting method \_SB.PCI0.LPCB.EC._Q26 due to previous error (AE_NOT_FOUND) (20250807/psparse-529)
[29435.547714] scsi 0:0:0:0: Direct-Access     USB      Mass Storage     1.99 PQ: 0 ANSI: 2
[29435.548526] sd 0:0:0:0: Attached scsi generic sg0 type 0
[29435.549131] sd 0:0:0:0: [sda] 262144 512-byte logical blocks: (134 MB/128 MiB)
[29435.549504] sd 0:0:0:0: [sda] Write Protect is off
[29435.549509] sd 0:0:0:0: [sda] Mode Sense: 03 00 00 00
[29435.549919] sd 0:0:0:0: [sda] No Caching mode page found
[29435.549922] sd 0:0:0:0: [sda] Assuming drive cache: write through
[29435.566684] sd 0:0:0:0: [sda] Attached SCSI removable disk

**Comment by grulja** [comment]
> I can only be FMV's fault, it is the only thing I have ever used the stick for. As I said, once to put Fedora KDE on there and once from Fedora KDE to put Fedora Workstation on there. It wasn't a cheap $1 stick from Alibaba, it was a regular $9 one from the local tech store

Thank you for providing the `dmesg` log. I looked through the output with the help of Gemini, and it shows that the USB drive is reporting a total capacity of only 128 MB. This typically happens when there is physical damage to the drive, either to the microcontroller or the NAND flash chip. Writing an OS image is a sustained, intensive task. If a drive has poor thermal dissipation, a microscopic crack in a solder joint, or defective NAND memory cells, the heat and heavy workload can cause it to fail mid-write. Additionally, the log identifies your drive as a generic, unbranded USB device, which sometimes points to lower-quality internal components that are more prone to these hardware failures. Because the kernel is reporting this as physical hardware damage, I believe you should be able to get the drive replaced for a new one under warranty.
