### ISSUE TITLE
Can't run on Windows 10

### ISSUE THREAD

**Issue by markfaine** [FedoraQt/MediaWriter#653]
![image](https://github.com/FedoraQt/MediaWriter/assets/949949/f8c0afa8-dbf3-4c2d-91e3-64d6cdb5687b)

**Comment by grulja** [comment]
This is because builds you download here are not signed. We are working on officially signed builds for Windows and we already have signed builds for older versions, but our certificate has expired and with the new one the signing process is now more complicated. See https://github.com/FedoraQt/MediaWriter/issues/641.

You should still be able to run it even when it's not signed, isn't there an option to show more and click "I accept the risk" or something like that?

**Comment by markfaine** [comment]
> You should still be able to run it even when it's not signed, isn't there an option to show more and click "I accept the risk" or something like that?

There is on a regular consumer installation but most corporate domains disable that ability.
