### ISSUE TITLE
MacOS Arm - FMW 5.0.9 is damaged and can't be opened

### ISSUE THREAD

**Issue by NullBadger** [FedoraQt/MediaWriter#678]
On attempting to launch FMW I receive the error:

“FedoraMediaWriter.app” is damaged and can’t be opened. You should move it to the Trash."

At first I installed [via homebrew ](https://formulae.brew.sh/cask/fedora-media-writer#default) and later I removed and re-downloaded the arm build from the 5.0.9 assets directly. I still receive the error.

**Comment by grulja** [comment]
Does the non-arm build work for you instead? I sadly have now way to verify it since my only MacBook is still intel based.

**Comment by parasaito** [comment]
Hey I tried using it. It works. Need to remove the quarantine attribute from downloaded image. 
`xattr -r -d com.apple.quarantine FedoraMediaWriter.app`
Absolutely not my preferred way to run binaries on my computer.

Would appreciate if you could provide a signed and notarized binary for ARM mac since Gatekeeper doesn't really like the current build and reports as **damaged**.

**Comment by NullBadger** [comment]
@parasaito , this allowed the app to launch. I'm a bit apprehensive on why/how though. I'm not familiar with xattr -r -d and am not sure of it's implications. Thanks!

**Comment by parasaito** [comment]
@NullBadger Every executable file you download via a browser on macOS is given the quarantine attribute. Gatekeeper verifies if the binary is signed and notarized when you first load the executable. This FMW image is currently neither signed nor notarized currently, and that's why gatekeeper prompts it might be damaged (notarization requires getting an Apple developer account subscription).

You can check such things with [Apparency](https://www.mothersruin.com/software/Apparency/)

Here's the preview for FMW 5.0.9 :

<img width="808" alt="Screenshot 2024-02-05 at 10 10 43 AM" src="https://github.com/FedoraQt/MediaWriter/assets/97852663/c6ec1ea2-6661-42c1-8dc8-58fcacef15c0">


---


Here's another app that's notarized :

<img width="805" alt="image" src="https://github.com/FedoraQt/MediaWriter/assets/97852663/51525a9c-9a16-4820-b261-cee01e4e0fa5">

---

The `xattr -r -d` **r**ecursively **d**eletes the quarantine extended attribute from the disk image so gatekeeper check is bypassed. That's all. I do not condone it's use blindly on any app, only use it on apps you trust.
